### PR TITLE
FEATURE: garbage collector final

### LINKED ISSUE #181: Garbage Collector
- [x] Should remove orphaned Files or FileInfos. 

- [x] Check if a group still exist. If not: delete all files and directories from the group. [Can use deleteService.deleteFolder]

### PR DESCRIPTION
**Pull request by realemx**
Ready, but error prone because of all the methods without permission check.

closes #181

### CODE REVIEW

**Comment by iTitus** [comment]
if services get changed we need to update the documentation

**Comment by realemx** [comment]
> if services get changed we need to update the documentation.
> doesnt have to be now, but should be done before the 6th
It is still questionable, if they will be changed. The the comment under #181

**Comment by iTitus** [comment]
I'd like the approach via a custom self-created account with the admin role.

**Comment by realemx** [comment]
Then there's another question: hard coded in the SecurityService or an entry fixed in the schema.sql.

**Comment by iTitus** [comment]
You don't need to edit the database. Just create an `Account`

**Comment by realemx** [comment]
Yep, totally forgot about simply creating an object and just thought about fetching one. You're right. :taco:

**Pull request closed without merging**
