### PR TITLE
REFACTOR: use annotation based keycloak testing

### PR DESCRIPTION
**Pull request by iTitus**

### CODE REVIEW

**Comment by Segelzwerg** [comment]
holy shit, that works?!

**Comment by iTitus** [comment]
Everyone bless @sogal100 from RocketChat!

**Comment by iTitus** [comment]
Everyone bless @sotgasotga

**Comment by Segelzwerg** [comment]
4.1 in documentation is about the previous controller test. This could be rewrote or even deleted.

**Pull request merged**
