### PR TITLE
Update Links in README

### PR DESCRIPTION
**Pull request by iTitus**
Necromancing for the memes :)

### CODE REVIEW

**Comment by Segelzwerg** [comment]
What about the checks? Otherwise lgtm

**Comment by realemx** [comment]
f*cking necrophiles, .... but LGTM! :+1: :100: :100:

**Comment by iTitus** [comment]
Yeah, the CI ist just broken

**Comment by iTitus** [comment]
I'll try to fix

**Comment by aerzqii** [comment]
Z00phi13s, p3d0phi13s, n3cr0phi13s, SCREW THEM

**Pull request merged**
